backend:
  name: git-gateway
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: 'pages'
    label: 'Home Page Sections'
    files:
      - label: 'About'
        name: 'about'
        file: 'content/pages/home/sections/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Get Involved'
        name: 'get-involved'
        file: 'content/pages/home/sections/get-involved.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Merch'
        name: 'merch'
        file: 'content/pages/home/sections/merch.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Disable Ordering?', name: disable, widget: 'boolean' }

  - name: 'faq'
    label: 'FAQ'
    files:
      - label: 'Top Section'
        name: 'top-section'
        file: 'content/pages/faq/top-section.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'FAQ Entries'
        name: 'faq-entries'
        file: 'content/pages/faq/entries.yml'
        fields:
        - label: "FAQ Entries"
          name: "entries"
          widget: "list"
          required: false
          fields: 
            - label: "Question"
              name: "question"
              widget: "string"
            - label: "Answer"
              name: "answer"
              widget: "markdown"

  - name: 'press'
    label: 'Press'
    files:
      - label: 'Top Section'
        name: 'top-section'
        file: 'content/pages/press/top-section.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Press Links'
        name: 'press-entries'
        file: 'content/pages/press/media-links.json'
        fields:
        - label: "Press Entries"
          name: "entries"
          widget: "list"
          required: false
          fields: 
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Publisher"
              name: "publisher"
              widget: "string"
            - label: "Date"
              name: "date"
              widget: "datetime"
            - label: "URL"
              name: "url"
              widget: "string"
            - label: "Publication Logo/Image"
              name: "image"
              widget: "image"
            - label: "snippet"
              name: "snippet"
              widget: "string"

  - label: "Tiny Porch Dates"
    name: "tiny-porch-dates"
    folder: "content/dates"
    format: "yml"
    extension: "yml"
    identifier_field: "month"
    create: true
    fields:
      - label: "Month"
        name: "month" 
        widget: "string"
        required: false
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Image/Map"
        name: "image"
        widget: "image"
      - label: "Image Alt Text"
        name: "alt"
        widget: "text"
        default: "Map"
      - label: "Food Vendors"
        name: "food_vendors"
        widget: "list"
        required: false
        fields: 
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - {label: "Location", name: "location", widget: "string", required: false}
      - label: "Porches"
        name: "porches"
        widget: "list"
        required: false
        fields: 
          - label: "Address"
            name: "address"
            widget: "string"
            required: false
          - label: "Performers"
            name: "performers"
            widget: "list"
            required: false
            fields: 
            - {label: "Name", name: "name", widget: "string", required: false}
            - {label: "Link", name: "link", widget: "string", required: false}
            - {label: "Show Time", name: "logo", widget: "string", required: false}
