backend:
  name: git-gateway
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: 'pages'
    label: 'Home Page Sections'
    files:
      - label: 'About'
        name: 'about'
        file: 'content/pages/home/sections/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      # - label: 'About'
      #   name: 'about'
      #   file: 'content/about.md'
      #   fields:
      #     - { label: 'Title', name: 'title', widget: 'string' }
      #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      #     - { label: 'Body', name: 'body', widget: 'markdown' }