backend:
  name: git-gateway
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: 'pages'
    label: 'Home Page Sections'
    files:
      - label: 'About'
        name: 'about'
        file: 'content/pages/home/sections/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Get Involved'
        name: 'get-involved'
        file: 'content/pages/home/sections/get-involved.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Merch'
        name: 'merch'
        file: 'content/pages/home/sections/merch.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Disable Ordering?', name: disable, widget: 'boolean' }
  - label: "Tiny Porch Dates"
    name: "tiny-porch-dates"
    folder: "content/dates"
    identifier_field: "month"
    create: true
    fields:
      - label: "Month"
        name: "month" 
        widget: "string"
        required: false
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Image/Map"
        name: "image"
        widget: "image"
      - label: "Image Alt Text"
        name: "alt"
        widget: "text"
        default: "Map"
      - label: "Food Vendors"
        name: "food_vendors"
        widget: "list"
        required: false
        fields: 
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - {label: "Location", name: "location", widget: "string", required: false}
      - label: "Porches"
        name: "porches"
        widget: "list"
        required: false
        fields: 
          - label: "Address"
            name: "address"
            widget: "string"
            required: false
          - label: "Performers"
            name: "performers"
            widget: "list"
            required: false
            fields: 
            - {label: "Name", name: "name", widget: "string", required: false}
            - {label: "Link", name: "link", widget: "string", required: false}
            - {label: "Show Time", name: "logo", widget: "string", required: false}
